<?php

/**
 * BaseName
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * 
 * @method string getName() Returns the current record's "name" value
 * @method Name   setName() Sets the current record's "name" value
 * 
 * @package    test
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id$
 */
abstract class BaseName extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('name');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}