<?php

/**
 * Name
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    test
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id$
 */
class Name extends BaseName
{
  const BROKEN_LETTER = 'a';
  const REPLACE_LETTER = 'o';
  
  protected $fixed_name;
  
  public function endWith($letter = self::BROKEN_LETTER)
  {
    $name = $this->getName();
    
    return $name[strlen($name) - 1] == $letter;   
  }
  
  public function getPrefix()
  {
    if ($this->endWith())
    {
      return 'Hello';
    }
    else
    {
      return 'Hi';
    }
  }
  
  public function getFixedName()
  {
    if (is_null($this->fixed_name))
    {
      $name = $this->getName();
      
      if ($this->endWith())
      {
        $name[strlen($name) - 1] = self::REPLACE_LETTER;
      }
      
      $this->fixed_name = $name;
    }
    
    return $this->fixed_name;
  }
  
  public function sayHello()
  {
    return $this->getPrefix().' '.$this->getFixedName();
  }
  
  public function __toString()
  {
    return $this->sayHello();
  }
}